export const TRENDING_PROJECTS = [
  {
    id: '1',
    title: 'Autonomous Rover MK-IV',
    description: 'Full SLAM navigation system with LiDAR + computer vision for outdoor terrain mapping and obstacle avoidance.',
    category: 'Robotics',
    difficulty: 'Advanced',
    tags: ['ROS2', 'Python', 'LiDAR', 'OpenCV'],
    likes: 56, views: 312, comments: 12,
    author: { name: 'Youssef A.', avatar: 'YA', color: 'from-arc-400 to-plasma-500' },
    image: null, featured: true,
    gradient: 'from-blue-50 to-green-50',
    accentColor: '#005fcc',
  },
  {
    id: '2',
    title: 'Neural Motor Controller',
    description: 'High-performance BLDC motor controller with FOC algorithm, implemented on STM32 with CAN bus interface.',
    category: 'Electronics',
    difficulty: 'Advanced',
    tags: ['STM32', 'C++', 'FOC', 'CAN Bus'],
    likes: 42, views: 278, comments: 8,
    author: { name: 'Omar T.', avatar: 'OT', color: 'from-plasma-400 to-arc-600' },
    image: null, featured: false,
    gradient: 'from-green-50 to-emerald-50',
    accentColor: '#009933',
  },
  {
    id: '3',
    title: 'Smart Home Hub v3',
    description: 'ESP32-based home automation hub with local AI inference, web dashboard, and Matter protocol support.',
    category: 'IoT',
    difficulty: 'Intermediate',
    tags: ['ESP32', 'Matter', 'AI', 'React'],
    likes: 31, views: 190, comments: 7,
    author: { name: 'Sara E.', avatar: 'SE', color: 'from-void-400 to-arc-500' },
    image: null, featured: false,
    gradient: 'from-indigo-50 to-blue-50',
    accentColor: '#3399ff',
  },
  {
    id: '4',
    title: 'FPV Drone Racing Build',
    description: 'Complete 5-inch freestyle drone build guide with custom FC firmware, telemetry and in-depth PID tuning.',
    category: 'Drones',
    difficulty: 'Intermediate',
    tags: ['Betaflight', 'FPV', 'Soldering', 'PID'],
    likes: 67, views: 405, comments: 15,
    author: { name: 'Manal N.', avatar: 'MN', color: 'from-arc-500 to-void-400' },
    image: null, featured: false,
    gradient: 'from-sky-50 to-indigo-50',
    accentColor: '#005fcc',
  },
  {
    id: '5',
    title: 'Robotic Arm 6-DOF',
    description: '3D-printed 6-axis robotic arm with inverse kinematics, ROS2 MoveIt! integration and force feedback.',
    category: 'Robotics',
    difficulty: 'Advanced',
    tags: ['ROS2', 'MoveIt', 'Python', '3D Print'],
    likes: 88, views: 530, comments: 18,
    author: { name: 'Ahmed K.', avatar: 'AK', color: 'from-plasma-500 to-arc-400' },
    image: null, featured: false,
    gradient: 'from-green-50 to-teal-50',
    accentColor: '#009933',
  },
  {
    id: '6',
    title: 'AI Vision Pipeline',
    description: 'Real-time object detection and tracking pipeline running on Jetson Nano with custom YOLOv8 models.',
    category: 'AI & ML',
    difficulty: 'Advanced',
    tags: ['YOLO', 'Jetson', 'CUDA', 'Python'],
    likes: 29, views: 156, comments: 6,
    author: { name: 'Lena M.', avatar: 'LM', color: 'from-arc-400 to-plasma-600' },
    image: null, featured: true,
    gradient: 'from-blue-50 to-violet-50',
    accentColor: '#005fcc',
  },
]

export const CATEGORIES = [
  { id: 'robotics',    label: 'Robotics',    icon: '🤖', count: 38 },
  { id: 'electronics', label: 'Electronics', icon: '⚡', count: 27 },
  { id: 'ai-ml',       label: 'AI & ML',     icon: '🧠', count: 21 },
  { id: 'iot',         label: 'IoT',         icon: '📡', count: 19 },
  { id: 'drones',      label: 'Drones',      icon: '🚁', count: 14 },
  { id: 'mechanical',  label: 'Mechanical',  icon: '⚙️', count: 9 },
]

export const STATS = [
  { value: '128',  label: 'Projects Published', real: true },
  { value: '3',    label: 'Categories Live',    real: true },
  { value: '312',  label: 'Engineers Joined',   real: true },
  { value: '100%', label: 'Open Source',        real: true },
  { value: 'Beta', label: 'Early Access',       real: true, isBeta: true },
]

export const FEATURES = [
  { icon:'BookOpen', title:'Learn from the Best',   description:'Step-by-step builds, guides, and real-world documentation from expert engineers.', accent:'plasma' },
  { icon:'Code2',    title:'Full Source Access',     description:'Schematics, CAD files, source code, and fabrication tips — all in one place.',    accent:'arc' },
  { icon:'Users',    title:'Collaborate',            description:'Get feedback, collaborate with a global community, and grow together.',            accent:'plasma' },
  { icon:'Award',    title:'Showcase Work',          description:'Publish your builds and inspire the next generation of engineers.',                accent:'arc' },
]
